name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}  # on all machines specified
    strategy:
        fail-fast: false
        matrix:
            config:
            - {
                name: "Ubuntu_latest_gcc-14",
                os: ubuntu-latest,
                build_type: "Release",
                cc: "gcc",
                cxx: "g++",
                generators: "Ninja"
            }

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies on Ubuntu_latest_gcc-14
      if: startsWith(matrix.config.name, 'Ubuntu_latest_gcc-14')
      run: |
        echo =============== Install dependencies ==========================
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git wget unzip
        echo =============== Prepare workspace =============================
        echo "Workspace: ${{github.workspace}}"
        echo "Build type: ${{env.BUILD_TYPE}}"
        echo "CMake generator: ${{matrix.config.generators}}"
        echo "CC: ${{matrix.config.cc}}"
        echo "CXX: ${{matrix.config.cxx}}"

        mkdir -p ${{github.workspace}}/build
        mkdir -p ${{github.workspace}}/build/tests
        cp -r ${{github.workspace}}/tests/data ${{github.workspace}}/build/tests
        echo =============== Update gcc ======================================
        echo gcc version before:
        gcc --version
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install ninja-build gcc-14 g++-14
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 91 --slave /usr/bin/g++ g++ /usr/bin/g++-14 --slave /usr/bin/gcov gcov /usr/bin/gcov-14
        echo gcc version after
        gcc --version
        echo =============== Get BOOST =======================================
        sudo apt-get update
        sudo apt-get install libboost-all-dev
        echo =============== Finished installing dependencies ================
#        echo =============== Update ninja ====================================
#        echo ninja version before
#        ninja --version
#        wget https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
#        sudo unzip ninja-linux.zip -d /usr/local/bin/
#        sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force
#        echo ninja version after
#        ninja --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ${{github.workspace}}/tests/unittests

    - uses: actions/upload-artifact@v4
      with:
        name: libutils-${{ matrix.config.os }}.a
        path: ${{github.workspace}}/lib/libutils.a
